-- Add 'pending_validation' to the feedback.status enum.
-- The original CHECK constraint generated by drizzle's text({ enum: [...] })
-- doesn't include the new value, so writes fail without this update.

ALTER TABLE feedback DROP CONSTRAINT IF EXISTS feedback_status_check;
ALTER TABLE feedback ADD CONSTRAINT feedback_status_check
  CHECK (status IN ('open', 'in_progress', 'pending_validation', 'resolved', 'dismissed'));
